### ISSUE TITLE
1_algoseek_minute_data.py

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#108]
running the above code returning the following errors:

`Traceback (most recent call last):
  File "1_algoseek_minute_data.py", line 259, in <module>
    extract_and_combine_data()
  File "1_algoseek_minute_data.py", line 240, in extract_and_combine_data
    for i, f in tqdm(enumerate(list(as_path.glob('*/**/*.csv.gz')))):
NameError: name 'as_path' is not defined`

I changed the as_path to path and got the following error:

`0it [00:00, ?it/s]
Traceback (most recent call last):
  File "1_algoseek_minute_data.py", line 259, in <module>
    extract_and_combine_data()
  File "1_algoseek_minute_data.py", line 241, in extract_and_combine_data
    data.append(pd.read_csv(f, parse_dates=[['Date', 'TimeBarStart']])
  File "/home/ubuntu/anaconda3/envs/ml4t/lib/python3.8/site-packages/pandas/core/frame.py", line 4724, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['date_time'] are in the columns"`

**Comment by Eeonum** [comment]
You need to change the date_time to date_timebarstart

**Comment by stefan-jansen** [comment]
That's right, sorry, had only test with an intermediate dataset where I had already renamed some columns, going to push the update shortly.
