### ISSUE TITLE
mamba env update -n ml4t -f ml4t-base.yml has multiple error when installing

### ISSUE THREAD

**Issue by lililinuk** [stefan-jansen/machine-learning-for-trading#258]
I have followed the installation instruction and got the below error : 

**\ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\latex_envs\__init__.py", line 3, in <module>
    from . import latex_envs
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\latex_envs\latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\__init__.py", line 4, in <module>
    from .exporters import *
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\exporters\__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\exporters\html.py", line 12, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\jinja2\__init__.py)

- Config option `kernel_spec_manager_class` not recognized by `EnableJupyterNbextensionsConfiguratorApp`.
Enabling: jupyter_nbextensions_configurator
- Writing config: C:\Users\Administrator\anaconda3\envs\ml4t\etc\jupyter
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Enabling tree nbextension nbextensions_configurator/tree_tab/main...

- Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\ml4t\Scripts\jupyter-contrib-nbextension-script.py", line 6, in <module>
    from jupyter_contrib_nbextensions.application import main
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\jupyter_contrib_nbextensions\application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\jupyter_contrib_nbextensions\install.py", line 12, in <module>
    import latex_envs
ModuleNotFoundError: No module named 'latex_envs'

done
ERROR conda.core.link:_execute(730): An error occurred while installing package 'conda-forge::jupyter_latex_envs-1.4.6-py38haa244fe_1001'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package conda-forge::jupyter_latex_envs-1.4.6-py38haa244fe_1001
location of failed script: C:\Users\Administrator\anaconda3\envs\ml4t\Scripts\.jupyter_latex_envs-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\latex_envs\__init__.py", line 3, in <module>
    from . import latex_envs
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\latex_envs\latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\__init__.py", line 4, in <module>
    from .exporters import *
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\exporters\__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\exporters\html.py", line 12, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\jinja2\__init__.py)

==> script output <==
stdout:
C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET DISTUTILS_USE_SDK=1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET MSSdk=1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET "VS_VERSION=15.0"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET "VS_MAJOR=15"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET "VS_YEAR=2017"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "MSYS2_ENV_CONV_EXCL=CL"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "PY_VCRUNTIME_REDIST=C:\Users\Administrator\anaconda3\envs\ml4t\bin\vcruntime140.dll"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "CXX=cl.exe"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "CC=cl.exe"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "VSINSTALLDIR="

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "NEWER_VS_WITH_OLDER_VC=0"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>for /F "usebackq tokens=*" %i in (`vswhere.exe -nologo -products * -version [15.0,16.0) -property installationPath`) do (set "VSINSTALLDIR=%i\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "" (for /F "usebackq tokens=*" %i in (`vswhere.exe -nologo -products * -requires Microsoft.VisualStudio.Component.VC.v141.x86.x64 -property installationPath`) do (
set "VSINSTALLDIR=%i\"
 set "NEWER_VS_WITH_OLDER_VC=1"
) )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF NOT "" == "" (
set "INCLUDE=;"
 set "LIB=;"
 set "CMAKE_PREFIX_PATH=;"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>call :GetWin10SdkDir

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>call :GetWin10SdkDirHelper HKLM\SOFTWARE\Wow6432Node  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKCU\SOFTWARE\Wow6432Node  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKLM\SOFTWARE  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKCU\SOFTWARE  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 exit /B 1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>exit /B 0

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>for /F %i in ('dir /ON /B "\include\10.*"') DO (SET WindowsSDKVer=%~i )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 (echo "Didn't find any windows 10 SDK. I'm not sure if things will work, but let's try..." )  else (echo Windows SDK version found as: "" )
Windows SDK version found as: ""

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF "win-64" == "win-64" (
set "BITS=64"
 set "CMAKE_PLAT=x64"
)  ELSE (
set "BITS=32"
 set "CMAKE_PLAT=Win32"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF 2017 GEQ 2019 (
set "CMAKE_GEN=Visual Studio 15 2017"
 set "USE_NEW_CMAKE_GEN_SYNTAX=1"
)  ELSE (
IF "win-64" == "win-64" (set "CMAKE_GEN=Visual Studio 15 2017 Win64" )  else (set "CMAKE_GEN=Visual Studio 15 2017" )
 set "USE_NEW_CMAKE_GEN_SYNTAX=0"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>echo "NEWER_VS_WITH_OLDER_VC=0"
"NEWER_VS_WITH_OLDER_VC=0"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF "0" == "1" (
set "CMAKE_GEN=Visual Studio 16 2019"
 set "USE_NEW_CMAKE_GEN_SYNTAX=1"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF "Visual Studio 15 2017 Win64" == "" SET "CMAKE_GENERATOR=Visual Studio 15 2017 Win64"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF "0" == "1" (
IF "" == "" SET "CMAKE_GENERATOR_PLATFORM=x64"
 IF "" == "" SET "CMAKE_GENERATOR_TOOLSET=v141"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>pushd C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>CALL "VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.16

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>popd

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>call :GetWin10SdkDirHelper HKLM\SOFTWARE\Wow6432Node  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKCU\SOFTWARE\Wow6432Node  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKLM\SOFTWARE  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKCU\SOFTWARE  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 exit /B 1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>exit /B 0

stderr: The system cannot find the file specified.
The system cannot find the path specified.
The system cannot find the path specified.

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda_env\cli\main_update.py", line 126, in execute
    result[installer_type] = installer.install(prefix, specs, args, env)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\mamba\mamba_env.py", line 95, in mamba_install
    conda_transaction.execute()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\link.py", line 281, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\link.py", line 744, in _execute
    raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package conda-forge::jupyter_latex_envs-1.4.6-py38haa244fe_1001
location of failed script: C:\Users\Administrator\anaconda3\envs\ml4t\Scripts\.jupyter_latex_envs-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\latex_envs\__init__.py", line 3, in <module>
    from . import latex_envs
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\latex_envs\latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\__init__.py", line 4, in <module>
    from .exporters import *
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\exporters\__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\nbconvert\exporters\html.py", line 12, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (C:\Users\Administrator\anaconda3\envs\ml4t\lib\site-packages\jinja2\__init__.py)

==> script output <==
stdout:
C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET DISTUTILS_USE_SDK=1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET MSSdk=1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET "VS_VERSION=15.0"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET "VS_MAJOR=15"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>SET "VS_YEAR=2017"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "MSYS2_ENV_CONV_EXCL=CL"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "PY_VCRUNTIME_REDIST=C:\Users\Administrator\anaconda3\envs\ml4t\bin\vcruntime140.dll"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "CXX=cl.exe"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "CC=cl.exe"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "VSINSTALLDIR="

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>set "NEWER_VS_WITH_OLDER_VC=0"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>for /F "usebackq tokens=*" %i in (`vswhere.exe -nologo -products * -version [15.0,16.0) -property installationPath`) do (set "VSINSTALLDIR=%i\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "" (for /F "usebackq tokens=*" %i in (`vswhere.exe -nologo -products * -requires Microsoft.VisualStudio.Component.VC.v141.x86.x64 -property installationPath`) do (
set "VSINSTALLDIR=%i\"
 set "NEWER_VS_WITH_OLDER_VC=1"
) )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\" )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF NOT "" == "" (
set "INCLUDE=;"
 set "LIB=;"
 set "CMAKE_PREFIX_PATH=;"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>call :GetWin10SdkDir

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>call :GetWin10SdkDirHelper HKLM\SOFTWARE\Wow6432Node  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKCU\SOFTWARE\Wow6432Node  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKLM\SOFTWARE  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKCU\SOFTWARE  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 exit /B 1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>exit /B 0

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>for /F %i in ('dir /ON /B "\include\10.*"') DO (SET WindowsSDKVer=%~i )

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 (echo "Didn't find any windows 10 SDK. I'm not sure if things will work, but let's try..." )  else (echo Windows SDK version found as: "" )
Windows SDK version found as: ""

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF "win-64" == "win-64" (
set "BITS=64"
 set "CMAKE_PLAT=x64"
)  ELSE (
set "BITS=32"
 set "CMAKE_PLAT=Win32"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF 2017 GEQ 2019 (
set "CMAKE_GEN=Visual Studio 15 2017"
 set "USE_NEW_CMAKE_GEN_SYNTAX=1"
)  ELSE (
IF "win-64" == "win-64" (set "CMAKE_GEN=Visual Studio 15 2017 Win64" )  else (set "CMAKE_GEN=Visual Studio 15 2017" )
 set "USE_NEW_CMAKE_GEN_SYNTAX=0"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>echo "NEWER_VS_WITH_OLDER_VC=0"
"NEWER_VS_WITH_OLDER_VC=0"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF "0" == "1" (
set "CMAKE_GEN=Visual Studio 16 2019"
 set "USE_NEW_CMAKE_GEN_SYNTAX=1"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF "Visual Studio 15 2017 Win64" == "" SET "CMAKE_GENERATOR=Visual Studio 15 2017 Win64"

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>IF "0" == "1" (
IF "" == "" SET "CMAKE_GENERATOR_PLATFORM=x64"
 IF "" == "" SET "CMAKE_GENERATOR_TOOLSET=v141"
)

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>pushd C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>CALL "VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.16

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>popd

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>call :GetWin10SdkDirHelper HKLM\SOFTWARE\Wow6432Node  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKCU\SOFTWARE\Wow6432Node  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKLM\SOFTWARE  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 call :GetWin10SdkDirHelper HKCU\SOFTWARE  1>nul 2>&1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>if errorlevel 1 exit /B 1

C:\Users\Administrator\anaconda3\envs\ml4t\Scripts>exit /B 0

stderr: The system cannot find the file specified.
The system cannot find the path specified.
The system cannot find the path specified.

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\Scripts\mamba-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\anaconda3\lib\site-packages\mamba\mamba.py", line 871, in main
    return mamba_env.main()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\mamba\mamba_env.py", line 105, in main
    return conda_env_main()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda_env\cli\main.py", line 91, in main
    return conda_exception_handler(do_call, args, parser)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 1374, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 1085, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 1116, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 1132, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 1136, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 1059, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "C:\Users\Administrator\anaconda3\lib\logging\__init__.py", line 1471, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\logging\__init__.py", line 1585, in _log
    self.handle(record)
  File "C:\Users\Administrator\anaconda3\lib\logging\__init__.py", line 1594, in handle
    if (not self.disabled) and self.filter(record):
  File "C:\Users\Administrator\anaconda3\lib\logging\__init__.py", line 807, in filter
    result = f.filter(record)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\gateways\logging.py", line 61, in filter
    record.msg = record.msg % new_args
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\__init__.py", line 132, in __repr__
    errs.append(e.__repr__())
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\__init__.py", line 71, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\__init__.py", line 90, in __str__
    return text_type(self.message % self._kwargs)
TypeError: %i format: a number is required, not dict**

I have also tried 

mamba env update -n ml4t -f installation/windows/ml4t.yml 

PS. after conda env create -n ml4t python=3.8 , my jupyter note book doesn't appear ml4t kernal, so I am not sure if this is installed successfully ? 

Thank you.

**Comment by stefan-jansen** [comment]
If you are having trouble installing all libraries in one go, please just install the libraries that you are actually going to use for the notebooks you are planning to run. There is really no need to install a ton of libraries unless you are really going to run all of the notebooks in one go. It's much easier to just install the packages you need.
