### ISSUE TITLE
Error in training the agent: not enough values to unpack in trading_environment.step

### ISSUE THREAD

**Issue by Maathouse** [stefan-jansen/machine-learning-for-trading#277]
Hi!

I currently face the following error:

Traceback (most recent call last):
  File "c:\Users\marcm\OneDrive\Bureaublad\Programming\Maathouse Algorithm Trading\MachineLearning\Jansen\Deep_RL.py", line 263, in <module>
    next_state, reward, done, _ = trading_environment.step(action) 
  File "C:\Users\marcm\OneDrive\Bureaublad\Programming\Maathouse Algorithm Trading\MachineLearning\lib\site-packages\gym\wrappers\time_limit.py", line 50, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
ValueError: not enough values to unpack (expected 5, got 4)

Anyone faced the same problem or know how to solve it? Seems to be an error in one of the Core API for Environment, Wrapper, ActionWrapper, RewardWrapper and ObservationWrapper.

Regards,

Maathouse

**Comment by stefan-jansen** [comment]
The openAI gym API [changed [in version 0.26](https://github.com/openai/gym/releases/tag/0.26.0) to return an additional value. Please downgrade to an earlier version or modify the code accordingly.
