### ISSUE TITLE
do not have permission in /home/packt/ml4t

### ISSUE THREAD

**Issue by Yutwizard** [stefan-jansen/machine-learning-for-trading#39]
When I install via docker on windows10.

After input zipline ingest seem like permission to mkdir in /home/packt/ml4t is demied.
How can I add permission to this folder.

(ml4t-zipline) packt@6463f5cb63ce:~$ zipline ingest
Traceback (most recent call last):
  File "/opt/conda/envs/ml4t-zipline/bin/zipline", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/__main__.py", line 60, in main
    os.environ,
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 249, in load_extensions
    pth.ensure_file(default_extension_path)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/paths.py", line 58, in ensure_file
    ensure_directory_containing(path)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/paths.py", line 45, in ensure_directory_containing
    ensure_directory(os.path.dirname(path))
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/paths.py", line 30, in ensure_directory
    os.makedirs(path)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/packt/ml4t/data'

**Comment by Yutwizard** [comment]
finally I try to make it on linux all error was disappear.

**Comment by stefan-jansen** [comment]
See [here](https://medium.com/@Charles_Stover/fixing-volumes-in-docker-toolbox-4ad5ace0e572#fromHistory#fromHistory) for enabling access on Windows. I've also added this to the installation instructions.
